const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const number = new Intl.NumberFormat('zh-TW',{maximumFractionDigits:4});
let transactions = [], alerts=[], alertEvents=[], portfolio = {holdings:[],summary:{},baseCurrency:'TWD'}, history = {points:[],currency:'TWD'}, attribution={items:[],currency:'TWD'}, chartRange='1M', attributionRange='1Y', chartGeometry=[], searchTimer;

const formatMoney = (value, currency=portfolio.baseCurrency||'TWD') => new Intl.NumberFormat('zh-TW',{style:'currency',currency,maximumFractionDigits:currency==='TWD'?0:2}).format(value||0);
async function api(url, options={}) {
  const response = await fetch(url,{headers:{'Content-Type':'application/json'},...options});
  if (!response.ok) { const body=await response.json().catch(()=>({})); throw new Error(body.error||'操作失敗'); }
  return response.status===204 ? null : response.json();
}
async function load() {
  try {
    const params = new URLSearchParams();
    if ($('#filterSymbol').value) params.set('symbol',$('#filterSymbol').value);
    if ($('#filterFrom').value) params.set('from',$('#filterFrom').value);
    if ($('#filterTo').value) params.set('to',$('#filterTo').value);
    [portfolio,transactions,history,attribution,alerts,alertEvents] = await Promise.all([api('/api/portfolio'),api('/api/transactions?'+params),api('/api/portfolio/history?range='+chartRange),api('/api/portfolio/attribution?range='+attributionRange),api('/api/alerts'),api('/api/alert-events')]);
    render();
  } catch(err) { toast(err.message); }
}
function render(){renderSummary();renderChart();renderAttribution();renderHoldings();renderTransactions();renderReview();renderSymbolFilter();renderAlerts();$('#baseCurrency').value=portfolio.baseCurrency||'TWD'}
function pnlClass(v){return v>0?'positive':v<0?'negative':'neutral'}
function renderSummary(){const s=portfolio.summary;$('#totalValue').textContent=formatMoney(s.totalValue);$('#totalCost').textContent=formatMoney(s.totalCost);$('#realized').textContent=formatMoney(s.realized);$('#fxRate').textContent=portfolio.usdTwd?Number(portfolio.usdTwd).toFixed(3):'—';const p=s.unrealizedPercent||0;$('#totalPnl').className='change '+pnlClass(p);$('#totalPnl').textContent=(p>=0?'＋':'')+p.toFixed(2)+'%　'+formatMoney(s.unrealized)}
function renderHoldings(){$('#holdingCount').textContent=`${portfolio.holdings.length} 個項目`;$('#holdings').innerHTML=portfolio.holdings.length?portfolio.holdings.map(h=>`<article class="holding-card"><div class="holding-top"><div class="asset-id"><span class="asset-avatar">${escape(h.symbol).slice(0,3)}</span><span class="asset-name"><strong>${escape(h.name)}</strong><small>${escape(h.symbol)} <i class="market-badge">${h.market}</i></small></span></div><button class="price-edit" data-price="${escape(h.symbol)}" data-current="${h.currentPrice}" title="更新目前價格">✎</button></div><div class="holding-value"><strong>${formatMoney(h.marketValue)}</strong><span class="${pnlClass(h.unrealized)}">${h.unrealized>=0?'＋':''}${h.unrealizedPercent.toFixed(2)}%</span></div><div class="allocation-bar"><span style="width:${Math.min(h.allocation,100)}%"></span></div><div class="holding-footer"><span>${number.format(h.quantity)} 股 · 均價 ${formatMoney(h.averageCost,h.currency)}</span><span>${h.allocation.toFixed(1)}%</span></div></article>`).join(''):`<div class="empty"><strong>從第一筆交易開始</strong>新增買入紀錄後，持股與總值會自動出現在這裡。</div>`}
function renderTransactions(){$('#transactionRows').innerHTML=transactions.length?transactions.slice().reverse().map(t=>`<tr><td class="mono">${t.tradedAt}</td><td><strong>${escape(t.symbol)}</strong> <i class="market-badge">${t.market}</i><br><small>${escape(t.name)}</small></td><td><span class="pill ${t.type}">${t.type==='buy'?'買入':'賣出'}</span></td><td class="mono">${number.format(t.quantity)}</td><td class="mono">${formatMoney(t.price,t.currency)}</td><td class="mono">${formatMoney(t.quantity*t.price+t.fee,t.currency)}</td><td><div class="row-actions"><button data-edit="${t.id}" aria-label="編輯">✎</button><button data-delete="${t.id}" aria-label="刪除">×</button></div></td></tr>`).join(''):`<tr><td colspan="7"><div class="empty"><strong>沒有符合條件的交易</strong>調整篩選條件，或新增一筆交易。</div></td></tr>`}
function renderReview(){$('#reviewList').innerHTML=transactions.length?transactions.slice().reverse().map(t=>`<article class="review-item"><div class="review-date">${t.tradedAt}</div><div class="review-content"><strong>${escape(t.name)} <small>${escape(t.symbol)}</small> · ${t.type==='buy'?'買入':'賣出'}</strong><p>${escape(t.note)||'這筆交易沒有留下備註。'}</p></div><div class="review-number">${number.format(t.quantity)} × ${formatMoney(t.price,t.currency)}</div></article>`).join(''):`<div class="empty"><strong>還沒有決策可以回顧</strong>在每筆交易留下當時的想法，未來會很有價值。</div>`}
function renderSymbolFilter(){const current=$('#filterSymbol').value;const assets=[...new Map([...portfolio.holdings.map(h=>[h.symbol,h.name]),...transactions.map(t=>[t.symbol,t.name])]).entries()];$('#filterSymbol').innerHTML='<option value="">全部標的</option>'+assets.map(([s,n])=>`<option value="${escape(s)}">${escape(s)} · ${escape(n)}</option>`).join('');$('#filterSymbol').value=current}
const alertRuleNames={price_below:'價格跌到',price_above:'價格漲到',cost_loss_pct:'成本停損',cost_profit_pct:'成本停利',trailing_stop_pct:'移動停損'};
function renderAlerts(){const assets=[...new Map([...portfolio.holdings.map(h=>[h.symbol,h.name]),...transactions.map(t=>[t.symbol,t.name])]).entries()];$('#alertSymbol').innerHTML=assets.map(([s,n])=>`<option value="${escape(s)}">${escape(s)} · ${escape(n)}</option>`).join('');$('#alertList').innerHTML=alerts.length?alerts.map(a=>`<article class="alert-item ${a.active?'':'inactive'}"><div class="alert-detail"><strong>${escape(a.name)} · ${escape(a.symbol)}</strong><small>${alertRuleNames[a.ruleType]} ${a.ruleType.includes('pct')?a.value+'%':formatMoney(a.value,a.currency)}${a.ruleType==='trailing_stop_pct'?` · 最高 ${formatMoney(a.highWatermark,a.currency)}`:''}</small></div><div class="alert-price"><strong>${formatMoney(a.triggerPrice,a.currency)}</strong><small>目前觸發價</small></div><div class="alert-actions"><button data-alert-toggle="${a.id}" data-active="${!a.active}">${a.active?'暫停':'啟用'}</button><button data-alert-delete="${a.id}">刪除</button></div></article>`).join(''):'<div class="empty"><strong>還沒有價格提醒</strong>為持有的標的設定購入、停損、停利或移動停損。</div>';$('#alertEvents').innerHTML=alertEvents.length?alertEvents.map(e=>`<article class="alert-item"><div class="alert-detail"><strong>${escape(e.name)} · ${alertRuleNames[e.ruleType]}</strong><small>${new Date(e.triggeredAt).toLocaleString('zh-TW')}</small></div><div class="alert-price"><strong>${formatMoney(e.marketPrice,e.currency)}</strong><small>觸發價 ${formatMoney(e.triggerPrice,e.currency)}</small></div><div class="alert-actions">${e.isRead?'已讀':`<button data-event-read="${e.id}">標記已讀</button>`}</div></article>`).join(''):'<div class="empty"><strong>尚未觸發提醒</strong>符合條件後會出現在這裡。</div>';if('Notification'in window&&Notification.permission==='granted')for(const e of alertEvents.filter(x=>!x.isRead)){if(!sessionStorage.getItem('notified-'+e.id)){new Notification(`${e.symbol} 價格提醒`,{body:`目前 ${formatMoney(e.marketPrice,e.currency)}，已到達 ${alertRuleNames[e.ruleType]}條件`});sessionStorage.setItem('notified-'+e.id,'1')}}}
function setAlertValueLabel(){$('#alertValueLabel').textContent=$('#alertRule').value.includes('pct')?'比例（%）':'目標價格'}

function renderChart(){
  const canvas=$('#portfolioChart'),wrap=canvas.parentElement,points=history.points||[],dpr=window.devicePixelRatio||1,w=Math.max(wrap.clientWidth,300),h=Math.max(wrap.clientHeight,180);canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+'px';canvas.style.height=h+'px';const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);
  $('#chartEmpty').hidden=points.length>0;if(!points.length){chartGeometry=[];$('#chartDelta').textContent='從現在開始記錄資產變化';return}
  const pad={l:10,r:12,t:14,b:28},values=points.map(p=>p.value),minValue=Math.min(...values),maxValue=Math.max(...values),spread=Math.max(maxValue-minValue,Math.max(maxValue*.04,1)),low=minValue-spread*.18,high=maxValue+spread*.18;
  const x=i=>pad.l+(points.length===1 ? .5 : i/(points.length-1))*(w-pad.l-pad.r),y=value=>pad.t+(high-value)/(high-low)*(h-pad.t-pad.b);chartGeometry=points.map((p,i)=>({x:x(i),y:y(p.value),point:p}));
  ctx.strokeStyle='#e2e5de';ctx.lineWidth=1;ctx.setLineDash([3,5]);for(let i=0;i<3;i++){const gy=pad.t+i*(h-pad.t-pad.b)/2;ctx.beginPath();ctx.moveTo(pad.l,gy);ctx.lineTo(w-pad.r,gy);ctx.stroke()}ctx.setLineDash([]);
  const gradient=ctx.createLinearGradient(0,pad.t,0,h-pad.b);gradient.addColorStop(0,'rgba(29,91,67,.24)');gradient.addColorStop(1,'rgba(29,91,67,0)');ctx.beginPath();chartGeometry.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.lineTo(chartGeometry.at(-1).x,h-pad.b);ctx.lineTo(chartGeometry[0].x,h-pad.b);ctx.closePath();ctx.fillStyle=gradient;ctx.fill();
  ctx.beginPath();chartGeometry.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.strokeStyle='#1d5b43';ctx.lineWidth=2.2;ctx.lineJoin='round';ctx.lineCap='round';ctx.stroke();if(points.length===1){ctx.beginPath();ctx.arc(chartGeometry[0].x,chartGeometry[0].y,4,0,Math.PI*2);ctx.fillStyle='#1d5b43';ctx.fill()}
  ctx.fillStyle='#7d8982';ctx.font='10px "DM Mono"';ctx.textAlign='left';const start=new Date(points[0].capturedAt),end=new Date(points.at(-1).capturedAt);ctx.fillText(formatChartDate(start),pad.l,h-7);ctx.textAlign='right';ctx.fillText(formatChartDate(end),w-pad.r,h-7);
  const change=values.at(-1)-values[0],pct=values[0]?change/values[0]*100:0,delta=$('#chartDelta');delta.className='chart-delta '+(change>0?'up':change<0?'down':'');delta.textContent=points.length===1?'已建立第一個資產快照':`${change>=0?'＋':''}${formatMoney(change,history.currency)}（${change>=0?'＋':''}${pct.toFixed(2)}%）`;
}
function formatChartDate(date){return new Intl.DateTimeFormat('zh-TW',{month:'short',day:'numeric'}).format(date)}
function chartPointer(event){if(!chartGeometry.length)return;const rect=$('#portfolioChart').getBoundingClientRect(),clientX=event.touches?.[0]?.clientX??event.clientX,px=clientX-rect.left;let nearest=chartGeometry[0];for(const item of chartGeometry){if(Math.abs(item.x-px)<Math.abs(nearest.x-px))nearest=item}const tooltip=$('#chartTooltip');tooltip.hidden=false;tooltip.style.left=nearest.x+'px';tooltip.style.top=nearest.y+'px';tooltip.querySelector('strong').textContent=formatMoney(nearest.point.value,history.currency);tooltip.querySelector('span').textContent=new Intl.DateTimeFormat('zh-TW',{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(nearest.point.capturedAt))}
function renderAttribution(){const data=attribution||{},currency=data.currency||portfolio.baseCurrency,max=Math.max(...(data.items||[]).map(i=>Math.abs(i.contribution)),1);$('#attributionTotal').textContent=formatSigned(data.totalChange,currency);$('#attributionProfit').textContent=formatSigned(data.profitChange,currency);$('#attributionFlow').textContent=formatSigned(data.netFlow,currency);$('#attributionList').innerHTML=(data.items||[]).length?data.items.map(item=>{const width=Math.abs(item.contribution)/max*50,left=item.contribution>=0?50:50-width;return `<div class="attribution-row"><div class="attribution-label"><strong>${escape(item.name)}</strong><small>${escape(item.symbol)}</small></div><div class="contribution-track"><span class="contribution-bar ${item.contribution<0?'negative':''}" style="left:${left}%;width:${width}%"></span></div><span class="attribution-amount ${item.contribution<0?'loss':'gain'}">${formatSigned(item.contribution,currency)}</span><span class="attribution-percent">${item.percentage>=0?'＋':''}${item.percentage.toFixed(1)}%</span></div>`}).join(''):'<div class="attribution-empty">再累積一次行情或交易快照後，就能比較各標的的損益貢獻。</div>'}
function formatSigned(value,currency){const n=Number(value||0);return `${n>0?'＋':''}${formatMoney(n,currency)}`}

function toggleWarrant(){const warrant=$('#assetType').value==='warrant';$('#warrantFields').hidden=!warrant;for(const id of ['underlyingSymbol','expiryDate','strikePrice','exerciseRatio'])$('#'+id).required=warrant;if(warrant){$('#market').value='US';$('#currency').value='USD';$('#market').disabled=true;$('#currency').disabled=true}else{$('#market').disabled=false;$('#currency').disabled=false}}
function openTrade(t){$('#tradeForm').reset();$('#fee').value=0;$('#tradedAt').value=new Date().toLocaleDateString('en-CA');$('#tradeId').value='';$('#dialogTitle').textContent='新增交易';$('#currency').value='TWD';$('#assetType').value='stock';hideSearch();if(t){$('#dialogTitle').textContent='編輯交易';$('#tradeId').value=t.id;$('#symbol').value=t.symbol;$('#name').value=t.name;$('#market').value=t.market||'TW';$('#currency').value=t.currency||'TWD';$('#assetType').value=t.assetType||'stock';$('#underlyingSymbol').value=t.underlyingSymbol||'';$('#warrantType').value=t.warrantType||'call';$('#expiryDate').value=t.expiryDate||'';$('#strikePrice').value=t.strikePrice||'';$('#exerciseRatio').value=t.exerciseRatio||'';$('#quantity').value=t.quantity;$('#price').value=t.price;$('#fee').value=t.fee;$('#tradedAt').value=t.tradedAt;$('#note').value=t.note;document.querySelector(`input[name=type][value=${t.type}]`).checked=true}toggleWarrant();$('#tradeDialog').showModal()}
function closeTrade(){$('#tradeDialog').close();hideSearch()}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function escape(value){const d=document.createElement('div');d.textContent=String(value??'');return d.innerHTML}
function hideSearch(){$('#tickerResults').hidden=true;$('#tickerResults').innerHTML=''}
async function searchTicker(){const q=$('#symbol').value.trim();if(!q){hideSearch();return}try{const results=await api(`/api/markets/search?market=${$('#market').value}&q=${encodeURIComponent(q)}`);const box=$('#tickerResults');box.innerHTML=results.length?results.map((r,i)=>`<button type="button" data-result="${i}"><strong>${escape(r.symbol)}</strong><span>${escape(r.name)}</span></button>`).join(''):'<button type="button" disabled><span>找不到符合的股票</span></button>';box.hidden=false;box._results=results}catch(err){hideSearch();toast(err.message)}}

$$('.nav-item').forEach(b=>b.addEventListener('click',()=>{$$('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active-view'));$('#'+b.dataset.view).classList.add('active-view');const titles={overview:['PORTFOLIO OVERVIEW','投資總覽'],transactions:['TRANSACTION LEDGER','交易紀錄'],review:['DECISION REVIEW','投資 Review'],alerts:['PRICE ALERTS','價格提醒']};$('#eyebrow').textContent=titles[b.dataset.view][0];$('#pageTitle').textContent=titles[b.dataset.view][1]}));
$('#addTrade').addEventListener('click',()=>openTrade());$('#closeDialog').addEventListener('click',closeTrade);$('#cancelDialog').addEventListener('click',closeTrade);
$('#market').addEventListener('change',()=>{$('#currency').value=$('#market').value==='US'?'USD':'TWD';$('#symbol').value='';$('#name').value='';hideSearch()});
$('#assetType').addEventListener('change',()=>{toggleWarrant();$('#symbol').value='';$('#name').value='';hideSearch()});
$('#symbol').addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(searchTicker,300)});
$('#tickerResults').addEventListener('click',e=>{const button=e.target.closest('[data-result]');if(!button)return;const result=$('#tickerResults')._results[Number(button.dataset.result)];$('#symbol').value=result.symbol;$('#name').value=result.name;$('#market').value=result.market;$('#currency').value=result.currency;if(result.assetType){$('#assetType').value=result.assetType;toggleWarrant()}hideSearch()});
$('#tradeForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('#tradeId').value;const body={symbol:$('#symbol').value,name:$('#name').value,market:$('#market').value,currency:$('#currency').value,assetType:$('#assetType').value,underlyingSymbol:$('#underlyingSymbol').value,warrantType:$('#warrantType').value,expiryDate:$('#expiryDate').value,strikePrice:Number($('#strikePrice').value||0),exerciseRatio:Number($('#exerciseRatio').value||0),type:$('input[name=type]:checked').value,quantity:Number($('#quantity').value),price:Number($('#price').value),fee:Number($('#fee').value||0),tradedAt:$('#tradedAt').value,note:$('#note').value};try{await api(id?'/api/transactions/'+id:'/api/transactions',{method:id?'PUT':'POST',body:JSON.stringify(body)});closeTrade();toast(id?'交易已更新':'交易已新增');await load()}catch(err){toast(err.message)}});
$('#baseCurrency').addEventListener('change',async()=>{try{await api('/api/settings/base-currency',{method:'PUT',body:JSON.stringify({currency:$('#baseCurrency').value})});await load()}catch(err){toast(err.message)}});
$('#refreshPrices').addEventListener('click',async()=>{const button=$('#refreshPrices');button.classList.add('loading');button.textContent='↻ 更新中…';try{const result=await api('/api/markets/refresh',{method:'POST'});toast(result.failed.length?`已更新 ${result.updated} 個，${result.failed.length} 個失敗`:`已更新 ${result.updated} 個標的與匯率`);await load()}catch(err){toast(err.message)}finally{button.classList.remove('loading');button.textContent='↻ 最新更新'}});
$$('[data-range]').forEach(button=>button.addEventListener('click',async()=>{$$('[data-range]').forEach(b=>b.classList.remove('active'));button.classList.add('active');chartRange=button.dataset.range;try{history=await api('/api/portfolio/history?range='+chartRange);renderChart()}catch(err){toast(err.message)}}));
$$('[data-attribution-range]').forEach(button=>button.addEventListener('click',async()=>{$$('[data-attribution-range]').forEach(b=>b.classList.remove('active'));button.classList.add('active');attributionRange=button.dataset.attributionRange;try{attribution=await api('/api/portfolio/attribution?range='+attributionRange);renderAttribution()}catch(err){toast(err.message)}}));
$('#portfolioChart').addEventListener('pointermove',chartPointer);$('#portfolioChart').addEventListener('pointerdown',chartPointer);$('#portfolioChart').addEventListener('pointerleave',()=>$('#chartTooltip').hidden=true);$('#portfolioChart').addEventListener('touchmove',chartPointer,{passive:true});
new ResizeObserver(()=>renderChart()).observe($('#portfolioChart').parentElement);
document.addEventListener('click',async e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]'),price=e.target.closest('[data-price]');if(!e.target.closest('.ticker-field'))hideSearch();if(edit)openTrade(transactions.find(t=>t.id===Number(edit.dataset.edit)));if(del&&confirm('確定要刪除這筆交易嗎？')){try{await api('/api/transactions/'+del.dataset.delete,{method:'DELETE'});toast('交易已刪除');await load()}catch(err){toast(err.message)}}if(price){const value=prompt(`更新 ${price.dataset.price} 的目前價格`,price.dataset.current);if(value!==null&&!Number.isNaN(Number(value))){try{await api(`/api/assets/${encodeURIComponent(price.dataset.price)}/price`,{method:'PUT',body:JSON.stringify({price:Number(value)})});toast('目前價格已更新');await load()}catch(err){toast(err.message)}}}});
['filterSymbol','filterFrom','filterTo'].forEach(id=>$('#'+id).addEventListener('change',load));$('#clearFilters').addEventListener('click',()=>{$('#filterSymbol').value='';$('#filterFrom').value='';$('#filterTo').value='';load()});
$('#addAlert').addEventListener('click',()=>{if(!$('#alertSymbol').options.length){toast('請先新增一筆交易');return}$('#alertForm').reset();$('#alertOneShot').checked=true;setAlertValueLabel();$('#alertDialog').showModal()});
function closeAlertDialog(){$('#alertDialog').close()}$('#closeAlertDialog').addEventListener('click',closeAlertDialog);$('#cancelAlertDialog').addEventListener('click',closeAlertDialog);$('#alertRule').addEventListener('change',setAlertValueLabel);
$('#alertForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/api/alerts',{method:'POST',body:JSON.stringify({symbol:$('#alertSymbol').value,ruleType:$('#alertRule').value,value:Number($('#alertValue').value),oneShot:$('#alertOneShot').checked})});closeAlertDialog();toast('提醒已建立');await load()}catch(err){toast(err.message)}});
$('#checkAlerts').addEventListener('click',async()=>{try{const result=await api('/api/alerts/check',{method:'POST'});toast(result.triggered?`有 ${result.triggered} 個提醒已觸發`:'目前沒有觸發條件');await load()}catch(err){toast(err.message)}});
$('#enableNotifications').addEventListener('click',async()=>{if(!('Notification'in window)){toast('這個瀏覽器不支援系統通知');return}const permission=await Notification.requestPermission();toast(permission==='granted'?'系統通知已啟用':'未允許系統通知')});
$('#alerts').addEventListener('click',async e=>{const toggle=e.target.closest('[data-alert-toggle]'),del=e.target.closest('[data-alert-delete]'),read=e.target.closest('[data-event-read]');try{if(toggle)await api('/api/alerts/'+toggle.dataset.alertToggle,{method:'PUT',body:JSON.stringify({active:toggle.dataset.active==='true'})});if(del&&confirm('確定要刪除這個提醒嗎？'))await api('/api/alerts/'+del.dataset.alertDelete,{method:'DELETE'});if(read)await api('/api/alert-events/'+read.dataset.eventRead+'/read',{method:'PUT'});if(toggle||del||read)await load()}catch(err){toast(err.message)}});
load();
