const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const number = new Intl.NumberFormat('zh-TW',{maximumFractionDigits:4});
let transactions = [], alerts=[], alertEvents=[], liabilities=[], liabilityTransactions=[], cashAccounts=[], cashTransactions=[], portfolio = {holdings:[],summary:{},baseCurrency:'TWD'}, history = {points:[],currency:'TWD'}, attribution={items:[],currency:'TWD'}, chartRange='1M', attributionRange='1Y', attributionExpanded=false, chartGeometry=[], chartHoverIndex=null, searchTimer;

const formatMoney = (value, currency=portfolio.baseCurrency||'TWD') => new Intl.NumberFormat('zh-TW',{style:'currency',currency,maximumFractionDigits:currency==='TWD'?0:2}).format(value||0);
async function api(url, options={}) {
  const response = await fetch(url,{headers:{'Content-Type':'application/json'},...options});
  if (!response.ok) { const body=await response.json().catch(()=>({})); throw new Error(body.error||'操作失敗'); }
  return response.status===204 ? null : response.json();
}
async function load() {
  try {
    const params = new URLSearchParams();
    if ($('#filterSymbol').value) params.set('symbol',$('#filterSymbol').value);
    if ($('#filterFrom').value) params.set('from',$('#filterFrom').value);
    if ($('#filterTo').value) params.set('to',$('#filterTo').value);
    [portfolio,transactions,history,attribution,alerts,alertEvents,liabilities,liabilityTransactions,cashAccounts,cashTransactions] = await Promise.all([api('/api/portfolio'),api('/api/transactions?'+params),api('/api/portfolio/history?range='+chartRange),api('/api/portfolio/attribution?range='+attributionRange),api('/api/alerts'),api('/api/alert-events'),api('/api/liabilities'),api('/api/liability-transactions'),api('/api/cash-accounts'),api('/api/cash-transactions')]);
    render();
  } catch(err) { toast(err.message); }
}
function render(){renderSummary();renderChart();renderAttribution();renderHoldings();renderTransactions();renderReview();renderSymbolFilter();renderAlerts();renderCash();renderLiabilities();$('#baseCurrency').value=portfolio.baseCurrency||'TWD'}
function pnlClass(v){return v>0?'positive':v<0?'negative':'neutral'}
function renderSummary(){const s=portfolio.summary;$('#totalValue').textContent=formatMoney(s.netWorth);$('#grossAssets').textContent=formatMoney(s.totalValue);$('#totalLiabilities').textContent=formatMoney(s.totalLiabilities);$('#fxRate').textContent=portfolio.usdTwd?Number(portfolio.usdTwd).toFixed(3):'—';const p=s.unrealizedPercent||0;$('#totalPnl').className='change '+pnlClass(p);$('#totalPnl').textContent=(p>=0?'＋':'')+p.toFixed(2)+'%　投資損益 '+formatMoney(s.unrealized)}
function renderHoldings(){const isCrypto=h=>h.assetType==='crypto'||['BTC','ETH'].includes(h.symbol),assetRows=portfolio.holdings.filter(h=>h.assetType!=='warrant'&&!isCrypto(h)).slice().sort((a,b)=>b.marketValue-a.marketValue),cryptos=portfolio.holdings.filter(isCrypto).slice().sort((a,b)=>b.marketValue-a.marketValue),warrants=portfolio.holdings.filter(h=>h.assetType==='warrant').slice().sort((a,b)=>b.marketValue-a.marketValue),sum=items=>items.reduce((total,item)=>total+item.marketValue,0),holdingRow=h=>`<tr><td><strong>${escape(h.symbol)}</strong> <i class="market-badge">${h.market}</i><br><small>${escape(h.name)}</small></td><td class="mono">${number.format(h.quantity)}</td><td class="mono">${formatMoney(h.averageCost,h.currency)}</td><td class="mono">${formatMoney(h.currentPrice,h.currency)}</td><td class="mono">${formatMoney(h.marketValue)}</td><td class="mono ${h.unrealized>=0?'positive-text':'negative-text'}">${h.unrealized>=0?'＋':''}${formatMoney(h.unrealized)}<br><small>${h.unrealized>=0?'＋':''}${h.unrealizedPercent.toFixed(2)}%</small></td><td class="mono">${h.allocation.toFixed(1)}%</td><td><button class="price-edit" data-price="${escape(h.symbol)}" data-current="${h.currentPrice}" title="更新目前價格">✎</button></td></tr>`;$('#holdingCount').textContent=`${assetRows.length} 個項目`;$('#holdingTotal').textContent=`合計 ${formatMoney(sum(assetRows))}`;$('#holdings').innerHTML=assetRows.length?assetRows.map(holdingRow).join(''):`<tr><td colspan="8"><div class="empty"><strong>尚無一般持股</strong></div></td></tr>`;$('#warrantCount').textContent=`${warrants.length} 個部位`;$('#warrantTotal').textContent=`合計 ${formatMoney(sum(warrants))}`;$('#warrants').innerHTML=warrants.length?warrants.map(h=>`<tr><td><strong>${escape(h.underlyingSymbol)}</strong> ${escape(h.warrantType).toUpperCase()}<br><small>${escape(h.symbol)}</small></td><td><span class="pill ${h.quantity<0?'sell':'buy'}">${h.quantity<0?'Short':'Long'}</span></td><td class="mono">${number.format(Math.abs(h.quantity))}</td><td class="mono">${formatMoney(h.strikePrice,h.currency)}</td><td class="mono">${h.expiryDate}</td><td class="mono">${formatMoney(h.marketValue)}</td><td class="mono ${h.unrealized>=0?'positive-text':'negative-text'}">${h.unrealized>=0?'＋':''}${formatMoney(h.unrealized)}<br><small>${h.unrealized>=0?'＋':''}${h.unrealizedPercent.toFixed(2)}%</small></td><td><button class="price-edit" data-price="${escape(h.symbol)}" data-current="${h.currentPrice}" title="更新目前價格">✎</button></td></tr>`).join(''):`<tr><td colspan="8"><div class="empty"><strong>尚無權證部位</strong></div></td></tr>`;$('#cryptoCount').textContent=`${cryptos.length} 個項目`;$('#cryptoTotal').textContent=`合計 ${formatMoney(sum(cryptos))}`;$('#cryptos').innerHTML=cryptos.length?cryptos.map(holdingRow).join(''):`<tr><td colspan="8"><div class="empty"><strong>尚無加密貨幣部位</strong></div></td></tr>`}
const isBalanceAdjustment=t=>/^截圖餘額(?:調整|校正)/.test(t.note||''),visibleTransactions=()=>transactions.filter(t=>!isBalanceAdjustment(t));
function renderTransactions(){const rows=visibleTransactions();$('#transactionRows').innerHTML=rows.length?rows.slice().reverse().map(t=>`<tr><td class="mono">${t.tradedAt}</td><td><strong>${escape(t.symbol)}</strong> <i class="market-badge">${t.market}</i><br><small>${escape(t.name)}</small></td><td><span class="pill ${t.type}">${t.type==='buy'?'買入':'賣出'}</span></td><td class="mono">${number.format(t.quantity)}</td><td class="mono">${formatMoney(t.price,t.currency)}</td><td class="mono">${formatMoney(t.quantity*t.price+t.fee,t.currency)}</td><td><div class="row-actions"><button data-edit="${t.id}" aria-label="編輯">✎</button><button data-delete="${t.id}" aria-label="刪除">×</button></div></td></tr>`).join(''):`<tr><td colspan="7"><div class="empty"><strong>沒有符合條件的交易</strong>調整篩選條件，或新增一筆交易。</div></td></tr>`}
function renderReview(){const rows=visibleTransactions();$('#reviewList').innerHTML=rows.length?rows.slice().reverse().map(t=>`<article class="review-item"><div class="review-date">${t.tradedAt}</div><div class="review-content"><strong>${escape(t.name)} <small>${escape(t.symbol)}</small> · ${t.type==='buy'?'買入':'賣出'}</strong><p>${escape(t.note)||'這筆交易沒有留下備註。'}</p></div><div class="review-number">${number.format(t.quantity)} × ${formatMoney(t.price,t.currency)}</div></article>`).join(''):`<div class="empty"><strong>還沒有決策可以回顧</strong>在每筆交易留下當時的想法，未來會很有價值。</div>`}
function renderSymbolFilter(){const current=$('#filterSymbol').value;const assets=[...new Map([...portfolio.holdings.map(h=>[h.symbol,h.name]),...transactions.map(t=>[t.symbol,t.name])]).entries()];$('#filterSymbol').innerHTML='<option value="">全部標的</option>'+assets.map(([s,n])=>`<option value="${escape(s)}">${escape(s)} · ${escape(n)}</option>`).join('');$('#filterSymbol').value=current}
const alertRuleNames={price_below:'價格跌到',price_above:'價格漲到',cost_loss_pct:'成本停損',cost_profit_pct:'成本停利',trailing_stop_pct:'移動停損'};
function renderAlerts(){const assets=[...new Map([...portfolio.holdings.map(h=>[h.symbol,h.name]),...transactions.map(t=>[t.symbol,t.name])]).entries()];$('#alertSymbol').innerHTML=assets.map(([s,n])=>`<option value="${escape(s)}">${escape(s)} · ${escape(n)}</option>`).join('');$('#alertList').innerHTML=alerts.length?alerts.map(a=>`<article class="alert-item ${a.active?'':'inactive'}"><div class="alert-detail"><strong>${escape(a.name)} · ${escape(a.symbol)}</strong><small>${alertRuleNames[a.ruleType]} ${a.ruleType.includes('pct')?a.value+'%':formatMoney(a.value,a.currency)}${a.ruleType==='trailing_stop_pct'?` · 最高 ${formatMoney(a.highWatermark,a.currency)}`:''}</small></div><div class="alert-price"><strong>${formatMoney(a.triggerPrice,a.currency)}</strong><small>目前觸發價</small></div><div class="alert-actions"><button data-alert-toggle="${a.id}" data-active="${!a.active}">${a.active?'暫停':'啟用'}</button><button data-alert-delete="${a.id}">刪除</button></div></article>`).join(''):'<div class="empty"><strong>還沒有價格提醒</strong>為持有的標的設定購入、停損、停利或移動停損。</div>';$('#alertEvents').innerHTML=alertEvents.length?alertEvents.map(e=>`<article class="alert-item"><div class="alert-detail"><strong>${escape(e.name)} · ${alertRuleNames[e.ruleType]}</strong><small>${new Date(e.triggeredAt).toLocaleString('zh-TW')}</small></div><div class="alert-price"><strong>${formatMoney(e.marketPrice,e.currency)}</strong><small>觸發價 ${formatMoney(e.triggerPrice,e.currency)}</small></div><div class="alert-actions">${e.isRead?'已讀':`<button data-event-read="${e.id}">標記已讀</button>`}</div></article>`).join(''):'<div class="empty"><strong>尚未觸發提醒</strong>符合條件後會出現在這裡。</div>';if('Notification'in window&&Notification.permission==='granted')for(const e of alertEvents.filter(x=>!x.isRead)){if(!sessionStorage.getItem('notified-'+e.id)){new Notification(`${e.symbol} 價格提醒`,{body:`目前 ${formatMoney(e.marketPrice,e.currency)}，已到達 ${alertRuleNames[e.ruleType]}條件`});sessionStorage.setItem('notified-'+e.id,'1')}}}
function setAlertValueLabel(){$('#alertValueLabel').textContent=$('#alertRule').value.includes('pct')?'比例（%）':'目標價格'}
const cashTypes={deposit:'存款／入金',withdrawal:'提款／出金',dividend:'股息',interest:'利息收入',fee:'手續費',adjustment:'其他調整'};
function renderCash(){const total=cashAccounts.reduce((s,x)=>s+x.balanceBase,0);$('#cashTotal').textContent=`合計 ${formatMoney(total)}`;$('#cashOverviewTotal').textContent=`合計 ${formatMoney(total)}`;$('#cashOverviewRows').innerHTML=cashAccounts.length?cashAccounts.map(x=>`<tr><td><strong>${escape(x.name)}</strong></td><td class="mono">${escape(x.currency)}</td><td class="mono">${formatMoney(x.balance,x.currency)}</td><td class="mono">${formatMoney(x.balanceBase)}</td><td>${escape(x.note)||'—'}</td></tr>`).join(''):'<tr><td colspan="5"><div class="empty"><strong>目前沒有現金帳戶</strong></div></td></tr>';$('#cashAccountList').innerHTML=cashAccounts.length?cashAccounts.map(x=>`<article class="alert-item"><div class="alert-detail"><strong>${escape(x.name)}</strong><small>${escape(x.currency)}${x.note?' · '+escape(x.note):''}</small></div><div class="alert-price"><strong>${formatMoney(x.balance,x.currency)}</strong><small>目前餘額</small></div></article>`).join(''):'<div class="empty"><strong>目前沒有現金帳戶</strong></div>';$('#cashRows').innerHTML=cashTransactions.length?cashTransactions.map(x=>`<tr><td class="mono">${x.tradedAt}</td><td>${escape(x.name)}</td><td>${cashTypes[x.type]}</td><td class="mono">${formatMoney(x.amount,x.currency)}</td><td>${escape(x.note)}</td></tr>`).join(''):'<tr><td colspan="5"><div class="empty"><strong>尚無現金流水</strong></div></td></tr>'}
const liabilityTypes={borrow:'新增借款',repay:'還款',interest:'利息',adjustment:'其他增加'},liabilityCategories={mortgage:'房貸',loan:'貸款',credit_card:'信用卡',other:'其他'};
function renderLiabilities(){const total=liabilities.reduce((sum,x)=>sum+x.balanceBase,0);$('#liabilityTotal').textContent=`合計 ${formatMoney(total)}`;$('#liabilityOverviewTotal').textContent=`合計 ${formatMoney(total)}`;$('#liabilityOverviewRows').innerHTML=liabilities.length?liabilities.map(x=>`<tr><td><strong>${escape(x.name)}</strong></td><td>${liabilityCategories[x.category]||'其他'}</td><td class="mono">${escape(x.currency)}</td><td class="mono">${formatMoney(x.balance,x.currency)}</td><td class="mono">${formatMoney(x.balanceBase)}</td><td class="mono">${number.format(x.interestRate)}%</td></tr>`).join(''):'<tr><td colspan="6"><div class="empty"><strong>目前沒有負債</strong>新增房貸、貸款或其他負債後，淨資產會自動扣除。</div></td></tr>';$('#liabilityList').innerHTML=liabilities.length?liabilities.map(x=>`<article class="alert-item"><div class="alert-detail"><strong>${escape(x.name)}</strong><small>${liabilityCategories[x.category]||'其他'} · 年利率 ${number.format(x.interestRate)}%${x.note?' · '+escape(x.note):''}</small></div><div class="alert-price"><strong>${formatMoney(x.balance,x.currency)}</strong><small>目前餘額</small></div><div class="alert-actions"><button data-liability-delete="${x.id}">刪除</button></div></article>`).join(''):'<div class="empty"><strong>目前沒有負債</strong>新增房貸、貸款或其他負債後，淨資產會自動扣除。</div>';$('#liabilityTxLiability').innerHTML=liabilities.map(x=>`<option value="${x.id}">${escape(x.name)} · ${formatMoney(x.balance,x.currency)}</option>`).join('');$('#liabilityRows').innerHTML=liabilityTransactions.length?liabilityTransactions.map(x=>`<tr><td class="mono">${x.tradedAt}</td><td>${escape(x.name)}</td><td><span class="pill ${x.type==='repay'?'buy':'sell'}">${liabilityTypes[x.type]}</span></td><td class="mono">${x.type==='repay'?'−':'＋'}${formatMoney(x.amount,x.currency)}</td><td>${escape(x.note)}</td><td><button class="price-edit" data-liability-tx-delete="${x.id}">×</button></td></tr>`).join(''):'<tr><td colspan="6"><div class="empty"><strong>尚無負債異動</strong>借款、利息或還款會顯示在這裡。</div></td></tr>'}

function renderChart(){
  const canvas=$('#portfolioChart'),wrap=canvas.parentElement,points=history.points||[],dpr=window.devicePixelRatio||1,w=Math.max(wrap.clientWidth,300),h=Math.max(wrap.clientHeight,180);canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+'px';canvas.style.height=h+'px';const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);
  $('#chartEmpty').hidden=points.length>0;if(!points.length){chartGeometry=[];$('#chartDelta').textContent='從現在開始記錄資產變化';return}
  const periodNames={"7D":"近 7 天","1M":"近 1 個月","3M":"近 3 個月","ALL":"全部期間"};$('#chartPeriod').textContent=`期間：${periodNames[chartRange]} · ${history.currency||portfolio.baseCurrency}`;const pad={l:78,r:12,t:14,b:28},values=points.map(p=>p.value),minValue=Math.min(...values),maxValue=Math.max(...values),spread=Math.max(maxValue-minValue,Math.max(maxValue*.04,1)),low=minValue-spread*.18,high=maxValue+spread*.18;
  const x=i=>pad.l+(points.length===1 ? .5 : i/(points.length-1))*(w-pad.l-pad.r),y=value=>pad.t+(high-value)/(high-low)*(h-pad.t-pad.b);chartGeometry=points.map((p,i)=>({x:x(i),y:y(p.value),point:p}));
  ctx.strokeStyle='#e2e5de';ctx.lineWidth=1;ctx.setLineDash([3,5]);ctx.fillStyle='#7d8982';ctx.font='10px "DM Mono"';ctx.textAlign='right';for(let i=0;i<3;i++){const gy=pad.t+i*(h-pad.t-pad.b)/2;ctx.beginPath();ctx.moveTo(pad.l,gy);ctx.lineTo(w-pad.r,gy);ctx.stroke();ctx.fillText(formatMoney(high-(high-low)*i/2,history.currency),pad.l-8,gy+3)}ctx.setLineDash([]);
  const gradient=ctx.createLinearGradient(0,pad.t,0,h-pad.b);gradient.addColorStop(0,'rgba(29,91,67,.24)');gradient.addColorStop(1,'rgba(29,91,67,0)');ctx.beginPath();chartGeometry.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.lineTo(chartGeometry.at(-1).x,h-pad.b);ctx.lineTo(chartGeometry[0].x,h-pad.b);ctx.closePath();ctx.fillStyle=gradient;ctx.fill();
  ctx.beginPath();chartGeometry.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.strokeStyle='#1d5b43';ctx.lineWidth=2.2;ctx.lineJoin='round';ctx.lineCap='round';ctx.stroke();if(points.length===1){ctx.beginPath();ctx.arc(chartGeometry[0].x,chartGeometry[0].y,4,0,Math.PI*2);ctx.fillStyle='#1d5b43';ctx.fill()}
  if(chartHoverIndex!==null&&chartGeometry[chartHoverIndex]){const p=chartGeometry[chartHoverIndex];ctx.strokeStyle='#64756c';ctx.lineWidth=1;ctx.setLineDash([3,3]);ctx.beginPath();ctx.moveTo(p.x,pad.t);ctx.lineTo(p.x,h-pad.b);ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.arc(p.x,p.y,4,0,Math.PI*2);ctx.fillStyle='#1d5b43';ctx.fill();ctx.strokeStyle='#fffefa';ctx.lineWidth=2;ctx.stroke()}
  ctx.fillStyle='#7d8982';ctx.font='10px "DM Mono"';const ticks=[0,Math.floor((points.length-1)/2),points.length-1].filter((v,i,a)=>a.indexOf(v)===i);ticks.forEach((i,idx)=>{ctx.textAlign=idx===0?'left':idx===ticks.length-1?'right':'center';ctx.fillText(formatChartDate(new Date(points[i].capturedAt)),chartGeometry[i].x,h-7)});
  const change=values.at(-1)-values[0],pct=values[0]?change/values[0]*100:0,delta=$('#chartDelta');delta.className='chart-delta '+(change>0?'up':change<0?'down':'');delta.textContent=points.length===1?'已建立第一個資產快照':`${change>=0?'＋':''}${formatMoney(change,history.currency)}（${change>=0?'＋':''}${pct.toFixed(2)}%）`;
}
function formatChartDate(date){return new Intl.DateTimeFormat('zh-TW',{month:'short',day:'numeric'}).format(date)}
function chartPointer(event){if(!chartGeometry.length)return;const rect=$('#portfolioChart').getBoundingClientRect(),clientX=event.touches?.[0]?.clientX??event.clientX,px=clientX-rect.left;let nearest=chartGeometry[0],index=0;for(const [i,item] of chartGeometry.entries()){if(Math.abs(item.x-px)<Math.abs(nearest.x-px)){nearest=item;index=i}}chartHoverIndex=index;renderChart();nearest=chartGeometry[index];const tooltip=$('#chartTooltip');tooltip.hidden=false;tooltip.style.left=nearest.x+'px';tooltip.style.top=nearest.y+'px';tooltip.querySelector('strong').textContent=formatMoney(nearest.point.value,history.currency);tooltip.querySelector('span').textContent=new Intl.DateTimeFormat('zh-TW',{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(nearest.point.capturedAt))}
function renderAttribution(){const data=attribution||{},currency=data.currency||portfolio.baseCurrency,max=Math.max(...(data.items||[]).map(i=>Math.abs(i.contribution)),1);$('#attributionTotal').textContent=formatSigned(data.totalChange,currency);$('#attributionProfit').textContent=formatSigned(data.profitChange,currency);$('#attributionFlow').textContent=formatSigned(data.netFlow,currency);$('#attributionList').innerHTML=(data.items||[]).length?data.items.map(item=>{const width=Math.abs(item.contribution)/max*50,left=item.contribution>=0?50:50-width;return `<div class="attribution-row"><div class="attribution-label"><strong>${escape(item.name)}</strong><small>${escape(item.symbol)}</small></div><div class="contribution-track"><span class="contribution-bar ${item.contribution<0?'negative':''}" style="left:${left}%;width:${width}%"></span></div><span class="attribution-amount ${item.contribution<0?'loss':'gain'}">${formatSigned(item.contribution,currency)}</span><span class="attribution-percent">${item.percentage>=0?'＋':''}${item.percentage.toFixed(1)}%</span></div>`}).join(''):'<div class="attribution-empty">再累積一次行情或交易快照後，就能比較各標的的損益貢獻。</div>'}
function formatSigned(value,currency){const n=Number(value||0);return `${n>0?'＋':''}${formatMoney(n,currency)}`}

function toggleWarrant(){const warrant=$('#assetType').value==='warrant';$('#warrantFields').hidden=!warrant;for(const id of ['underlyingSymbol','expiryDate','strikePrice','exerciseRatio'])$('#'+id).required=warrant;if(warrant){$('#market').value='US';$('#currency').value='USD';$('#market').disabled=true;$('#currency').disabled=true}else{$('#market').disabled=false;$('#currency').disabled=false}}
function openTrade(t){$('#tradeForm').reset();$('#fee').value=0;$('#tradedAt').value=new Date().toLocaleDateString('en-CA');$('#tradeId').value='';$('#dialogTitle').textContent='新增交易';$('#currency').value='TWD';$('#assetType').value='stock';hideSearch();if(t){$('#dialogTitle').textContent='編輯交易';$('#tradeId').value=t.id;$('#symbol').value=t.symbol;$('#name').value=t.name;$('#market').value=t.market||'TW';$('#currency').value=t.currency||'TWD';$('#assetType').value=t.assetType||'stock';$('#positionAction').value=t.positionAction||`${t.type}_open`;$('#underlyingSymbol').value=t.underlyingSymbol||'';$('#warrantType').value=t.warrantType||'call';$('#expiryDate').value=t.expiryDate||'';$('#strikePrice').value=t.strikePrice||'';$('#exerciseRatio').value=t.exerciseRatio||'';$('#quantity').value=t.quantity;$('#price').value=t.price;$('#fee').value=t.fee;$('#tradedAt').value=t.tradedAt;$('#note').value=t.note;document.querySelector(`input[name=type][value=${t.type}]`).checked=true}toggleWarrant();$('#tradeDialog').showModal()}
function closeTrade(){$('#tradeDialog').close();hideSearch()}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function escape(value){const d=document.createElement('div');d.textContent=String(value??'');return d.innerHTML}
function hideSearch(){$('#tickerResults').hidden=true;$('#tickerResults').innerHTML=''}
async function searchTicker(){const q=$('#symbol').value.trim();if(!q){hideSearch();return}try{const results=await api(`/api/markets/search?market=${$('#market').value}&q=${encodeURIComponent(q)}`);const box=$('#tickerResults');box.innerHTML=results.length?results.map((r,i)=>`<button type="button" data-result="${i}"><strong>${escape(r.symbol)}</strong><span>${escape(r.name)}</span></button>`).join(''):'<button type="button" disabled><span>找不到符合的股票</span></button>';box.hidden=false;box._results=results}catch(err){hideSearch();toast(err.message)}}

$$('.nav-item').forEach(b=>b.addEventListener('click',()=>{$$('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active-view'));$('#'+b.dataset.view).classList.add('active-view');const titles={overview:['PORTFOLIO OVERVIEW','投資總覽'],transactions:['TRANSACTION LEDGER','交易紀錄'],review:['DECISION REVIEW','投資 Review'],alerts:['PRICE ALERTS','價格提醒'],cash:['CASH LEDGER','現金流水'],liabilities:['LIABILITY LEDGER','負債紀錄']};$('#eyebrow').textContent=titles[b.dataset.view][0];$('#pageTitle').textContent=titles[b.dataset.view][1]}));
$('#addTrade').addEventListener('click',()=>openTrade());$('#closeDialog').addEventListener('click',closeTrade);$('#cancelDialog').addEventListener('click',closeTrade);
$('#market').addEventListener('change',()=>{$('#currency').value=$('#market').value==='US'?'USD':'TWD';$('#symbol').value='';$('#name').value='';hideSearch()});
$('#assetType').addEventListener('change',()=>{toggleWarrant();$('#symbol').value='';$('#name').value='';hideSearch()});
$('#symbol').addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(searchTicker,300)});
$('#tickerResults').addEventListener('click',e=>{const button=e.target.closest('[data-result]');if(!button)return;const result=$('#tickerResults')._results[Number(button.dataset.result)];$('#symbol').value=result.symbol;$('#name').value=result.name;$('#market').value=result.market;$('#currency').value=result.currency;if(result.assetType){$('#assetType').value=result.assetType;toggleWarrant()}hideSearch()});
$('#tradeForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('#tradeId').value,action=$('#positionAction').value,warrant=$('#assetType').value==='warrant';const body={symbol:$('#symbol').value,name:$('#name').value,market:$('#market').value,currency:$('#currency').value,assetType:$('#assetType').value,positionAction:warrant?action:'',underlyingSymbol:$('#underlyingSymbol').value,warrantType:$('#warrantType').value,expiryDate:$('#expiryDate').value,strikePrice:Number($('#strikePrice').value||0),exerciseRatio:Number($('#exerciseRatio').value||0),type:warrant?(action.startsWith('buy')?'buy':'sell'):$('input[name=type]:checked').value,quantity:Number($('#quantity').value),price:Number($('#price').value),fee:Number($('#fee').value||0),tradedAt:$('#tradedAt').value,note:$('#note').value};try{await api(id?'/api/transactions/'+id:'/api/transactions',{method:id?'PUT':'POST',body:JSON.stringify(body)});closeTrade();toast(id?'交易已更新':'交易已新增');await load()}catch(err){toast(err.message)}});
$('#baseCurrency').addEventListener('change',async()=>{try{await api('/api/settings/base-currency',{method:'PUT',body:JSON.stringify({currency:$('#baseCurrency').value})});await load()}catch(err){toast(err.message)}});
$('#refreshPrices').addEventListener('click',async()=>{const button=$('#refreshPrices');button.classList.add('loading');button.textContent='↻ 更新中…';try{const result=await api('/api/markets/refresh',{method:'POST'}),skipped=(result.skipped||[]).length;toast(result.failed.length?`已更新 ${result.updated} 個，${result.failed.length} 個失敗`:`已更新 ${result.updated} 個標的與匯率${skipped?`；${skipped} 個權證保留手動價格`:''}`);await load()}catch(err){toast(err.message)}finally{button.classList.remove('loading');button.textContent='↻ 最新更新'}});
$$('[data-range]').forEach(button=>button.addEventListener('click',async()=>{$$('[data-range]').forEach(b=>b.classList.remove('active'));button.classList.add('active');chartRange=button.dataset.range;try{history=await api('/api/portfolio/history?range='+chartRange);renderChart()}catch(err){toast(err.message)}}));
$$('[data-attribution-range]').forEach(button=>button.addEventListener('click',async()=>{$$('[data-attribution-range]').forEach(b=>b.classList.remove('active'));button.classList.add('active');attributionRange=button.dataset.attributionRange;try{attribution=await api('/api/portfolio/attribution?range='+attributionRange);renderAttribution()}catch(err){toast(err.message)}}));
$('#toggleAttribution').addEventListener('click',()=>{attributionExpanded=!attributionExpanded;$('#attributionContent').hidden=!attributionExpanded;$('#toggleAttribution').textContent=attributionExpanded?'收起分析':'展開分析';$('#toggleAttribution').setAttribute('aria-expanded',String(attributionExpanded))});
const chartCanvas=$('#portfolioChart'),hideChartTooltip=()=>{chartHoverIndex=null;$('#chartTooltip').hidden=true;renderChart()};
chartCanvas.addEventListener('pointermove',chartPointer);chartCanvas.addEventListener('mousemove',chartPointer);chartCanvas.addEventListener('pointerdown',chartPointer);chartCanvas.addEventListener('click',chartPointer);chartCanvas.addEventListener('pointerleave',hideChartTooltip);chartCanvas.addEventListener('mouseleave',hideChartTooltip);chartCanvas.addEventListener('touchmove',chartPointer,{passive:true});
new ResizeObserver(()=>renderChart()).observe($('#portfolioChart').parentElement);
document.addEventListener('click',async e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]'),price=e.target.closest('[data-price]');if(!e.target.closest('.ticker-field'))hideSearch();if(edit)openTrade(transactions.find(t=>t.id===Number(edit.dataset.edit)));if(del&&confirm('確定要刪除這筆交易嗎？')){try{await api('/api/transactions/'+del.dataset.delete,{method:'DELETE'});toast('交易已刪除');await load()}catch(err){toast(err.message)}}if(price){const value=prompt(`更新 ${price.dataset.price} 的目前價格`,price.dataset.current);if(value!==null&&!Number.isNaN(Number(value))){try{await api(`/api/assets/${encodeURIComponent(price.dataset.price)}/price`,{method:'PUT',body:JSON.stringify({price:Number(value)})});toast('目前價格已更新');await load()}catch(err){toast(err.message)}}}});
['filterSymbol','filterFrom','filterTo'].forEach(id=>$('#'+id).addEventListener('change',load));$('#clearFilters').addEventListener('click',()=>{$('#filterSymbol').value='';$('#filterFrom').value='';$('#filterTo').value='';load()});
$('#addAlert').addEventListener('click',()=>{if(!$('#alertSymbol').options.length){toast('請先新增一筆交易');return}$('#alertForm').reset();$('#alertOneShot').checked=true;setAlertValueLabel();$('#alertDialog').showModal()});
function closeAlertDialog(){$('#alertDialog').close()}$('#closeAlertDialog').addEventListener('click',closeAlertDialog);$('#cancelAlertDialog').addEventListener('click',closeAlertDialog);$('#alertRule').addEventListener('change',setAlertValueLabel);
$('#alertForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/api/alerts',{method:'POST',body:JSON.stringify({symbol:$('#alertSymbol').value,ruleType:$('#alertRule').value,value:Number($('#alertValue').value),oneShot:$('#alertOneShot').checked})});closeAlertDialog();toast('提醒已建立');await load()}catch(err){toast(err.message)}});
$('#checkAlerts').addEventListener('click',async()=>{try{const result=await api('/api/alerts/check',{method:'POST'});toast(result.triggered?`有 ${result.triggered} 個提醒已觸發`:'目前沒有觸發條件');await load()}catch(err){toast(err.message)}});
$('#enableNotifications').addEventListener('click',async()=>{if(!('Notification'in window)){toast('這個瀏覽器不支援系統通知');return}const permission=await Notification.requestPermission();toast(permission==='granted'?'系統通知已啟用':'未允許系統通知')});
$('#alerts').addEventListener('click',async e=>{const toggle=e.target.closest('[data-alert-toggle]'),del=e.target.closest('[data-alert-delete]'),read=e.target.closest('[data-event-read]');try{if(toggle)await api('/api/alerts/'+toggle.dataset.alertToggle,{method:'PUT',body:JSON.stringify({active:toggle.dataset.active==='true'})});if(del&&confirm('確定要刪除這個提醒嗎？'))await api('/api/alerts/'+del.dataset.alertDelete,{method:'DELETE'});if(read)await api('/api/alert-events/'+read.dataset.eventRead+'/read',{method:'PUT'});if(toggle||del||read)await load()}catch(err){toast(err.message)}});
$('#addLiability').addEventListener('click',()=>{$('#liabilityForm').reset();$('#liabilityRate').value=0;$('#liabilityDialog').showModal()});$$('[data-close-liability]').forEach(x=>x.addEventListener('click',()=>$('#liabilityDialog').close()));
$('#liabilityForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/api/liabilities',{method:'POST',body:JSON.stringify({name:$('#liabilityName').value,category:$('#liabilityCategory').value,currency:$('#liabilityCurrency').value,initialBalance:Number($('#liabilityInitial').value),interestRate:Number($('#liabilityRate').value||0),note:$('#liabilityNote').value})});$('#liabilityDialog').close();toast('負債已新增');await load()}catch(err){toast(err.message)}});
$('#addLiabilityTx').addEventListener('click',()=>{if(!liabilities.length){toast('請先新增負債項目');return}$('#liabilityTxForm').reset();$('#liabilityTxDate').value=new Date().toLocaleDateString('en-CA');$('#liabilityTxDialog').showModal()});$$('[data-close-liability-tx]').forEach(x=>x.addEventListener('click',()=>$('#liabilityTxDialog').close()));
$('#liabilityTxForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/api/liability-transactions',{method:'POST',body:JSON.stringify({liabilityId:Number($('#liabilityTxLiability').value),type:$('#liabilityTxType').value,amount:Number($('#liabilityTxAmount').value),tradedAt:$('#liabilityTxDate').value,note:$('#liabilityTxNote').value})});$('#liabilityTxDialog').close();toast('負債異動已新增');await load()}catch(err){toast(err.message)}});
$('#liabilities').addEventListener('click',async e=>{const liability=e.target.closest('[data-liability-delete]'),entry=e.target.closest('[data-liability-tx-delete]');try{if(liability&&confirm('刪除負債也會刪除全部異動紀錄，確定嗎？'))await api('/api/liabilities/'+liability.dataset.liabilityDelete,{method:'DELETE'});if(entry&&confirm('確定刪除這筆負債異動嗎？'))await api('/api/liability-transactions/'+entry.dataset.liabilityTxDelete,{method:'DELETE'});if(liability||entry)await load()}catch(err){toast(err.message)}});
load();
